# Main docker-compose file for the Stuttgart Wartezeiten project
# This file orchestrates all services: scraper, API, and frontend

services:
  scraper:
    build: 
      context: ../
      dockerfile: containers/scraper/Dockerfile
    container_name: stuttgart-scraper
    restart: always
    volumes:
      # Mount a volume to persist database and log files
      - ./data/scraper:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - stuttgart-network

  # Future API service (uncomment when ready)
  # api:
  #   build: 
  #     context: ../
  #     dockerfile: containers/api/Dockerfile
  #   container_name: stuttgart-api
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - scraper
  #   volumes:
  #     - ./data/scraper:/app/data:ro  # Read-only access to scraper data
  #   networks:
  #     - stuttgart-network

  # Future frontend service (uncomment when ready)
  # frontend:
  #   build: 
  #     context: ../
  #     dockerfile: containers/frontend/Dockerfile
  #   container_name: stuttgart-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   networks:
  #     - stuttgart-network

networks:
  stuttgart-network:
    driver: bridge

volumes:
  scraper_data:
