services:
  frontend:
    build:
      context: ../../
      dockerfile: containers/frontend/Dockerfile
    container_name: st_wait_frontend
    restart: unless-stopped
    networks:
      web_services:

networks:
  web_services:
    external: true
