services:
  api:
    build:
      context: ../../
      dockerfile: containers/api/Dockerfile
    container_name: st_wait_api
    volumes:
      - ../scraper/scraper_data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      web_services:

networks:
  web_services:
    external: true
